### ISSUE TITLE
Limitations or bug in initialization

### ISSUE THREAD

**Issue by cvermeulen88** [Cobanoglu-Lab/Haisu#1]
Dear authors,

I am trying to apply Haisu to a dataset with a lot of grouping, ie multiple sets of labels that are interconnected.
However, I can't seem to get the initialization working. 
I tested the example a little bit, and there is some behavior that I don't understand.
Is there a limitation to the amount of connections one is allowed to add in the adjacency matrix?

This works fine:
```
ajmatrix1 = np.zeros(shape=(len(label_set),len(label_set)))
ajmatrix1[5,1:10] = 1
haisu = HAISU(label_set, ajmatrix1)
```
This works fine:
```
ajmatrix2 = np.zeros(shape=(len(label_set),len(label_set)))
ajmatrix2[5,1:10] = 1
ajmatrix2[6,1:10] = 1
haisu = HAISU(label_set, ajmatrix2)
```
This gives an error:
```
ajmatrix3 = np.zeros(shape=(len(label_set),len(label_set)))
ajmatrix3[5,1:10] = 1
ajmatrix3[6,1:10] = 1
ajmatrix3[10,11:15] = 1
haisu = HAISU(label_set, ajmatrix3)
```
But this works again:
```
ajmatrix4 = np.zeros(shape=(len(label_set),len(label_set)))
ajmatrix4[5,1:10] = 1
#ajmatrix4[6,1:10] = 1
ajmatrix4[10,11:15] = 1
haisu = HAISU(label_set, ajmatrix4)
```

This is the error report I get form jupyter:

NodeNotFound                              Traceback (most recent call last)
<ipython-input-22-b7ca3665d50f> in <module>
      3 ajmatrix1[6,1:10] = 1
      4 ajmatrix1[10,11:15] = 1
----> 5 haisu = HAISU(label_set, ajmatrix1)
.../Haisu/Haisu.py in __init__(self, graph_labels, ajmatrix, disconnected_dist, avoid_self, self_dist, edge_weights)
     39         self.label_probs = []
     40         self.edge_weights = {}
---> 41         self._init_graph(graph_labels, ajmatrix,disconnected_dist, avoid_self, self_dist, edge_weights)
     42 
     43         # AUTO:

.../Haisu/Haisu.py in _init_graph(self, graph_labels, ajmatrix, disconnected_dist, avoid_self, self_dist, edge_weights)
     70             for j in range(self.graph.size()+1):
     71                 #path_len = 0 # disconnected default
---> 72                 if not nx.has_path(self.graph,i,j): continue#
     73                 path_len = nx.shortest_path_length(self.graph, i, j,weight=weight_func)
     74                 if path_len > self.max_shortestpath:

.../Haisu/haisu/lib/python3.8/site-packages/networkx/algorithms/shortest_paths/generic.py in has_path(G, source, target)
     31     """
     32     try:
---> 33         nx.shortest_path(G, source, target)
...
--> 221         raise nx.NodeNotFound(msg)
    222 
    223     # call helper to do the real work

NodeNotFound: Either source 0 or target 19 is not in G

**Comment by kevincvanhorn** [comment]
Hi, could you please try to clone the latest code in /staging branch and let me know if that works?

Another note is that these kind of adjacency matrices that you're producing may not be desirable. You can test what they look like by graphing manually or with `haisu.show_graph_info()`

Below is the code I tested with:

```
import networkx as nx
import numpy as np

s = 19 # size of label_set
ajmatrix = np.zeros(shape=(s,s))
ajmatrix[5,1:10] = 1
ajmatrix[6,1:10] = 1
ajmatrix[10,11:15] = 1

def weight_func(i,j,ddict):
    return ddict['weight']
nx.set_edge_attributes(graph, {}, 'weight')
graph = nx.from_numpy_matrix(ajmatrix)
nx.draw(graph,pos=nx.shell_layout(graph))
```

![image](https://user-images.githubusercontent.com/16003749/181271595-5526d00f-cb87-40ef-9dea-4be0b33c5834.png)


```
max_shortestpath=0
for i in range(s):
    for j in range(s):
        #path_len = 0 # disconnected default
        if not nx.has_path(graph,i,j): continue#
        path_len = nx.shortest_path_length(graph, i, j,weight=weight_func)
        if path_len > max_shortestpath:
            max_shortestpath = path_len

```

**Comment by cvermeulen88** [comment]
Hello Kevin,
Thank you for your reply and solution, indeed it works now!
I agree that it may not be desirable, as I'm making a group manually, but it's still fun to try.
With kind regards,
Carlo
